Kamino instructions to deposit and withdraw
GooseFX1/gamma-swap pull request #43
Opened 2024-12-26 06:15 UTC by SushantChandla

2024-12-30 16:12 UTC, 0xcrust requested changes
Looks good! Just a few things to address

2025-01-02 04:14 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +    let max_deposit_allowed =
I don't understand the addition.
See the amount to deposit/withdraw we calculate the max and then subtract that with what is deposited.
![Screenshot 2025-01-02 at 9 44 29 AM](https://github.com/user-attachments/assets/98929232-f08a-433d-b8e2-5b52c446736d)

2025-01-02 04:19 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +    let max_deposit_allowed =
`max_deposit_allowed_rate.div(FEE_RATE_DENOMINATOR_VALUE).mul(amount_in_pool_vault)`
yes, its the same. I will change to use checked_mul.
but `max_deposit_allowed_rate` * `amount_in_pool_vault` /`FEE_RATE_DENOMINATOR_VALUE` == `max_deposit_allowed_rate` * `FEE_RATE_DENOMINATOR_VALUE` / `amount_in_pool_vault` 

And In programming we should always prefer multiplying first as the numbers are `i64` and if we divide first we lose all the fraction points.
example: 
1 /100 * 120 with i64 will results in => 0 * 120 =0
if we did multiply first:
1 * 120 /100 => 120/100 => 1.20 => 1

2025-01-02 04:20 UTC, SushantChandla commented on programs/gamma/src/error.rs
> +    CannotChangeKaminoMarket,
Thanks, removed it was unused indeed

2025-01-02 23:23 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +    let amount_deposited = reserve.redeem_collateral_expected(collateral_amount)?;
You're right. This is better.

Just also saw that we can get how much we deposited with `reserve.collateral_to_liquidity(collateral_amount)`, which is pretty neat

2025-01-02 23:27 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +    let max_deposit_allowed =
This is wrong. The calculation we want is `(max_deposit_allowed_rate / FEE_RATE_DENOMINATOR_VALUE) * amount_in_pool_vault`

After we refactor this so multiplication comes first, it should be `(max_deposit_allowed_rate * amount_in_pool_vault) / FEE_RATE_DENOMINATOR_VALUE` 

Calculation can be done in u128 and final result converted back into a u64

2025-01-02 23:33 UTC, 0xcrust commented on programs/gamma/src/states/pool.rs
> +    pub token_0_amount_in_kamino: u64,
I agreed in a different thread that we don't need to store this. 

There's a simple method on the `Reserve` to get our exact deposit from our collateral-amount

2025-01-02 23:39 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +        // Deposit the difference between the max deposit allowed and the amount deposited.
Note should be `// Withdraw the difference between amount-deposited and max-deposit-allowed`

2025-01-02 23:44 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +    let amount_to_deposit_withdraw = if max_deposit_allowed < amount_deposited {
Should be greater-than(>), not less-than(<)

2025-01-02 23:48 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +            .checked_sub(amount_deposited)
Use `saturating_sub` to prevent an error here. The position might be at a loss

2025-01-02 23:55 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +    if !deposit_withdraw_amounts.is_withdrawing_profit {
As per other comments, we no longer need this block of code

2025-01-03 00:02 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +            deposit_withdraw_amounts.amount_to_deposit_withdraw,
For a withdrawal, we specify the `collateral_amount`, not `liquidity_amount`.

Hence, the argument here should be `reserve.collateral_exchange_rate()?.liquidity_to_collateral(amount_to_deposit_withdraw)`

2025-01-03 06:33 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +    let amount_deposited = reserve.redeem_collateral_expected(collateral_amount)?;
While I was writing the code I thought of the following case, so I went with storing the values:
If let's say for some reason the `collateral_amount` mint token values are reducing every day, by 10%, then each day we will try to deposit more and more each time the rebalance is called, to prevent his very rare case I decided to store it.

2025-01-03 08:17 UTC, 0xcrust commented on programs/gamma/src/states/pool.rs
> +    pub token_0_amount_in_kamino: u64,
Never mind. This should stay

2025-01-03 11:02 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +    let max_deposit_allowed =
ah, right!

2025-01-03 11:09 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +            .checked_sub(amount_deposited)
okay!

2025-01-03 11:40 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +        let amount_changed = if deposit_withdraw_amounts.should_deposit {
Isn't this just `amount_to_deposit_withdraw`?

2025-01-03 11:41 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +        let amount_changed = if deposit_withdraw_amounts.should_deposit {
no, as is also possible that we send `x` and only `x-dx` is actually deposited so we need to calculate it again.

2025-01-03 11:58 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +        let amount_changed = if deposit_withdraw_amounts.should_deposit {
What's the source for this claim? From reading the `klend` repo, it's exactly `liquidity_amount` that's transferred to the reserve

2025-01-03 12:19 UTC, 0xcrust approved these changes
Great work! LGTM

2025-01-03 12:20 UTC, 0xcrust commented on programs/gamma/src/instructions/rebalance.rs
> +    pub instruction_sysvar_account: AccountInfo<'info>,
UncheckedAccount<'info> and a `///CHECK:` note so anchor builds pass

2025-01-03 12:29 UTC, SushantChandla commented on programs/gamma/src/instructions/rebalance.rs
> +        let amount_changed = if deposit_withdraw_amounts.should_deposit {
Discussed in Slack.
Although what is suggested here works, we both agreed that the way we are doing it in code is also fool-proof, so going to let it as it is.

2025-01-03 12:43 UTC, merged